version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_SERVER=mongodb

  redis:
    image: redis
    restart: on-failure


  soeluma:
    image: ghcr.io/iamdavidonuh/soeluma:latest
    restart: on-failure
    depends_on:
      - redis
      - mongodb
    ports:
      - 3000:3000


volumes:
  mongo-data:
    driver: local

