name: Deploy to Heroku


on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          procfile: "web: yarn start"
        env:
          NODE_ENV: production
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}
          MONGODB_URI_LOCAL: ${{ secrets.MONGODB_URI_LOCAL }}
