name: soeluma-test-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.17.0, 12.20.1, 14.15.4]
        redis-version: [5]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Start Redis v${{ matrix.redis-version }}
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}
    #- name: Install Dependences
    - run: yarn install --frozen-lockfile
    - run: yarn test


