name: soeluma-test-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.17.0, 12.20.1, 14.15.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
     
    - name: Install Dependences
      cmd: yarn install --frozen-lockfile
      cmd: yarn test


